'use client';
import { useEffect, useState } from 'react';
import { CONTACT } from '@/lib/site-content';
export default function VisitDetails(){
  const [clock,setClock]=useState('NEW YORK'),[status,setStatus]=useState('REGULAR BOUTIQUE HOURS');
  const [copied,setCopied]=useState(false);
  const [copyError,setCopyError]=useState(false);
  useEffect(()=>{const update=()=>{const now=new Date();const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(now);const part=(name:string)=>parts.find(p=>p.type===name)?.value??'';const mins=Number(part('hour'))*60+Number(part('minute'));const day=part('weekday');const open=!['Sat','Sun'].includes(day)&&mins>=510&&mins<(day==='Fri'?990:1020);setClock(new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit',timeZoneName:'short'}).format(now));setStatus(open?'WITHIN REGULAR OPENING HOURS':'OUTSIDE REGULAR OPENING HOURS')};update();const timer=setInterval(update,60000);return()=>clearInterval(timer)},[]);
  const copy=async()=>{try{await navigator.clipboard.writeText('Grand Central Watch, 45th Street Passageway, next to Track 38, Grand Central Terminal, New York, NY 10017');setCopied(true);setCopyError(false)}catch{setCopied(false);setCopyError(true)}};
  return <div className="visit-details"><div className="live-clock"><span className="clock-indicator"/>{clock}<span>{status}</span></div><div className="visit-grid"><div><span className="atelier-label">THE BOUTIQUE</span><h2>Beside Track 38.<br/><em>At the heart of New York.</em></h2><address>45th Street Passageway<br/>Grand Central Terminal<br/>New York, NY 10017</address><button className="editorial-link" onClick={()=>void copy()}>{copied?'Address copied':'Copy boutique address'} <span>↗</span></button><output className={copyError?"copy-status":"sr-only"}>{copyError?"Copy is unavailable in this browser. Select the address above to copy it manually.":copied?'Boutique address copied to clipboard':''}</output><div className="contact-actions"><a href={CONTACT.tel}>Call {CONTACT.phone}</a><a href={`mailto:${CONTACT.email}`}>Email the atelier ↗</a><a href={CONTACT.sms}>Text a question ↗</a></div></div><div className="hours-table"><h3>Opening hours</h3>{[['Monday–Thursday','8:30 am – 5:00 pm'],['Friday','8:30 am – 4:30 pm'],['Saturday & Sunday','Closed']].map(([day,hours])=><div key={day}><span>{day}</span><span>{hours}</span></div>)}<p>New York local time. Holiday hours may differ; call before a special trip.</p><a className="solid-link" href="https://centralwatch.com/our-location">Maps & arrival photographs ↗</a></div></div></div>
}
